### ISSUE TITLE
./gradlew startMetacatCluster failed due to Cassandra unavailability 

### ISSUE THREAD

**Issue by lumengxi** [Netflix/metacat#198]
`./gradlew startMetacatCluster` or `./gradlew metacatPort` constantly fail because Cassandra take a few seconds to start: https://github.com/Netflix/metacat/blob/master/scripts/start_metacat_test_cluster.sh#L17 

A simple hack would be just adding a sleep here, or we can poke on the Cassandra port and wait until it is available. 

Is this repo accepting PRs right now? I can take a grab at this. Thanks for open sourcing this project!

**Comment by zhljen** [comment]
How much memory is allocated to the docker resource? The Cassandra container may not start if the memory is too small ( e.g. 2G).

**Comment by lumengxi** [comment]
@zhljen I am using all default configs. FWIW, the container does start, it just takes a few seconds. I was able to start up everything on a second pass.

**Comment by zhljen** [comment]
@lumengxi Thank you for helping metacat. The docker resource setting mentioned previously is the docker environment on the machine (e.g. laptop ) running this test. It's noticed that the Cassandra container may not start if the memory is too small, and increasing the memory setting will resolve this. Since the current setting works for us, I don't want to add extra sleep if not needed.

**Comment by lumengxi** [comment]
Yea I agreed. Closing this issue. Thanks for your response!
